Repository rwmt/Multiplayer, pull requests merged in 2024-04, with the labels that each got.

#428 First pass at RW 1.5
  About/About.xml
  Source/Client/AsyncTime/AsyncTimePatches.cs
  Source/Client/Comp/World/FactionWorldData.cs
  Source/Client/Debug/DebugActions.cs
  Source/Client/Debug/DebugPatches.cs
  Source/Client/Debug/DebugSync.cs
  Source/Client/EarlyPatches/SettingsPatches.cs
  Source/Client/Factions/FactionContextSetters.cs
  Source/Client/Factions/FactionCreationPatches.cs
  Source/Client/Factions/MultifactionPatches.cs
  Source/Client/Multiplayer.csproj
  Source/Client/MultiplayerGame.cs
  Source/Client/MultiplayerStatic.cs
  Source/Client/Patches/ArbiterPatches.cs
  Source/Client/Patches/Determinism.cs
  Source/Client/Patches/Feedback.cs
  Source/Client/Patches/LongEvents.cs
  Source/Client/Patches/Patches.cs
  Source/Client/Patches/Seeds.cs
  Source/Client/Patches/TickPatch.cs
  Source/Client/Patches/UniqueIds.cs
  Source/Client/Persistent/Rituals.cs
  Source/Client/Saving/CacheForReloading.cs
  Source/Client/Saving/CrossRefs.cs
  Source/Client/Saving/SaveCompression.cs
  Source/Client/Syncing/Dict/SyncDictDlc.cs
  Source/Client/Syncing/Dict/SyncDictRimWorld.cs
  Source/Client/Syncing/Game/SyncDelegates.cs
  Source/Client/Syncing/Game/SyncFields.cs
  Source/Client/Syncing/Game/SyncGame.cs
  Source/Client/Syncing/Game/SyncMarkers.cs
  Source/Client/Syncing/Game/SyncMethods.cs
  Source/Client/Syncing/Game/ThingFilterContexts.cs
  Source/Client/Syncing/Game/ThingFilterMarkers.cs
  Source/Client/Windows/TextAreaWindow.cs
  Source/Client/Windows/TwoTextAreasWindow.cs
  Source/Common/Version.cs
Labels: 1.5

#437 Fix exposing fields for SyncDelegates
  Source/Client/Syncing/Handler/SyncDelegate.cs
Labels: fix, 1.5

#436 Update current sync methods and delegates
  Source/Client/Syncing/Dict/SyncDictDlc.cs
  Source/Client/Syncing/Dict/SyncDictRimWorld.cs
  Source/Client/Syncing/Game/SyncDelegates.cs
  Source/Client/Syncing/Game/SyncMethods.cs
Labels: fix, 1.5

#435 Update external annotations
  Source/Client/ExternalAnnotations/0Harmony/Annotations.xml
  Source/Client/ExternalAnnotations/Assembly-CSharp/Annotations.xml
Labels: 1.5

#434 Replace Enumerable.Count(list) with list.Count
  Source/Client/Networking/JoinData.cs
  Source/Client/UI/IngameDebug.cs
  Source/Client/UI/MainMenuAnimation.cs
Labels: enhancement, low priority, 1.5

#439 Update RimWorld related dependencies
  Source/Client/Multiplayer.csproj
  Source/Client/Persistent/PersistentDialogs.cs
  Source/Common/Common.csproj
  Source/MultiplayerLoader/MultiplayerLoader.csproj
  Source/Server/Server.csproj
  Source/Tests/Tests.csproj
  Source/TestsOnMono/TestsOnMono.csproj
Labels: 1.5

#438 Sync majority of new gizmos added in 1.5/Anomaly
  Source/Client/Syncing/Dict/SyncDictRimWorld.cs
  Source/Client/Syncing/Game/SyncDelegates.cs
  Source/Client/Syncing/Game/SyncMethods.cs
  Source/Client/Syncing/Handler/SyncMethod.cs
Labels: 1.5, anomaly

#363 Added Ultrafast speed to TickRatePatch, changed if/else to switch
  Source/Client/AsyncTime/TickRatePatch.cs
Labels: enhancement

#406 Translate "Switch to map" string
  Source/Client/Persistent/ISwitchToMap.cs
Labels: 1.5

#441 Update MpMethodUtil
  Source/Client/Util/MpMethodUtil.cs
Labels: 1.5
