Repository rwmt/Multiplayer, pull requests merged in 2025-08, with the labels that each got.

#611 Fix: corpses do not rot
  Source/Client/AsyncTime/AsyncTimePatches.cs
Labels: fix, 1.6

#616 Fix Multifaction: Pawns Disappear When Caravan To Other Player Map
  Source/Client/MultiplayerStatic.cs
Labels: fix, multifaction, 1.6

#619 Fixes Transport pod exception
  Source/Client/MultiplayerStatic.cs
  Source/Client/Syncing/Dict/SyncDictRimWorld.cs
Labels: fix, 1.6

#622 Refactor: Removes Transport Pod Float Option Syncing
  Source/Client/Syncing/Dict/SyncDictRimWorld.cs
  Source/Client/Syncing/Game/SyncActions.cs
Labels: enhancement, 1.6

#623 Fix Cross OS Play Immediate Desync
  Source/Common/DeferredStackTracingImpl.cs
  Source/Common/Native.cs
Labels: fix, high priority, 1.6

#626 Refactor ThingsById system to use non static data
  Source/Client/Debug/DebugSync.cs
  Source/Client/Multiplayer.cs
  Source/Client/MultiplayerAPIBridge.cs
  Source/Client/MultiplayerGame.cs
  Source/Client/Saving/CrossRefs.cs
  Source/Client/Saving/ThingsById.cs
  Source/Client/Session/PlayerInfo.cs
  Source/Client/Syncing/Dict/SyncDictRimWorld.cs
  Source/Client/UI/CursorPatches.cs
Labels: fix, 1.5, 1.6

#630 Syncs Remaining Shuttle Behavior
  Source/Client/Syncing/Game/SyncDelegates.cs
  Source/Client/Syncing/Game/SyncMethods.cs
Labels: fix, 1.6

#631 Gravship Basic Behavior
  Source/Client/AsyncTime/AsyncWorldTimeComp.cs
  Source/Client/Comp/Map/MultiplayerMapComp.cs
  Source/Client/Patches/Feedback.cs
  Source/Client/Patches/GravshipTravelSessionPatches.cs
  Source/Client/Patches/VTRSyncPatch.cs
  Source/Client/Persistent/GravshipTravelSession.cs
  Source/Client/Syncing/Dict/SyncDictRimWorld.cs
  Source/Client/Syncing/Game/SyncDelegates.cs
  Source/Client/Syncing/Game/SyncMethods.cs
Labels: fix, 1.6, odyssey

#649 Use built-in constants for tick values
  Source/Client/ConstantTicker.cs
  Source/Client/Patches/Determinism.cs
  Source/Client/Syncing/Game/SyncDelegates.cs
  Source/Common/FreezeManager.cs
Labels: enhancement, low priority, 1.6

#650 Fix space maps being incorrectly considered paused/unpaused in certain circumstances
  Source/Client/AsyncTime/AsyncTimePatches.cs
Labels: fix, odyssey

#651 Remove anomaly check from colony subhuman check
  Source/Client/Factions/MultifactionPatches.cs
Labels: fix, low priority, 1.6

#652 Fix desyncs due to `PreceptComp_UnwillingToDo_Chance`
  Source/Client/Patches/Seeds.cs
Labels: fix, ideology, 1.6

#642 Refactor gravship implementation
  Source/Client/Patches/GravshipTravelSessionPatches.cs
  Source/Client/Persistent/GravshipTravelSession.cs
  Source/Client/Syncing/Dict/SyncDictRimWorld.cs
  Source/Client/Syncing/Game/SyncDelegates.cs
  Source/Client/Syncing/Game/SyncMethods.cs
Labels: enhancement, 1.6, odyssey

#656 Make world's travelling transporters smoother
  Source/Client/Patches/VTRSyncPatch.cs
Labels: enhancement, 1.6

#629 Patch TickManager for Chemical Dependency Gene
  Source/Client/AsyncTime/SetMapTime.cs
Labels: fix, 1.5

#660 Fix Gravship Launch Anchored Map Session Creation
  Source/Client/Patches/GravshipTravelSessionPatches.cs
  Source/Client/Persistent/GravshipTravelSession.cs
  Source/Client/Syncing/Game/SyncDelegates.cs
  Source/Client/Syncing/Game/SyncMethods.cs
Labels: fix, 1.6, odyssey
