Repository rwmt/Multiplayer, pull requests merged in 2025-07, with the labels that each got.

#476 Fix/sync CompObelisk_Abductor (Warped Obelisk/Labyrinth)
  Source/Client/Patches/LongEvents.cs
  Source/Client/Patches/Seeds.cs
Labels: fix, anomaly

#489 Rework FixNullMotes patch
  Source/Client/Patches/Determinism.cs
  Source/Client/Patches/Patches.cs
Labels: 1.5

#490 Fix starting bestowing ceremony using right-click
  Source/Client/Syncing/Game/SyncDelegates.cs
Labels: fix, royalty

#492 Exclude Spectator faction from FactionRepeater
  Source/Client/Factions/FactionRepeater.cs
Labels: fix, 1.5, multifaction

#494 Make AOE game condition causer use correct map time, fixes #210
  Source/Client/AsyncTime/SetMapTime.cs
Labels: fix, async, 1.5

#495 Sync atmospheric heater "reset" gizmo
  Source/Client/Syncing/Game/SyncDelegates.cs
  Source/Client/Syncing/Game/SyncMethods.cs
Labels: fix, 1.5

#497 Synced all research tab buttons, fixes #290
  Source/Client/Syncing/Dict/SyncDictRimWorld.cs
  Source/Client/Syncing/Game/SyncMethods.cs
Labels: fix, 1.5

#500 Register sync methods directly rather than using API
  Source/Client/Syncing/Game/SyncMethods.cs
Labels: low priority, 1.5

#502 Rework some PawnColumnWorker syncing
  Source/Client/AsyncTime/AsyncTimeComp.cs
  Source/Client/Patches/PawnTable.cs
  Source/Client/Syncing/Dict/SyncDictRimWorld.cs
  Source/Client/Syncing/Game/SyncMethods.cs
Labels: 1.5

#504 Update WorldObject sync worker delegate to handle pocket maps
  Source/Client/Syncing/Dict/SyncDictRimWorld.cs
Labels: fix, 1.5

#508 Improved starting experience for multifaction
  Source/Client/AsyncTime/AsyncTimeComp.cs
  Source/Client/AsyncTime/SetMapTime.cs
  Source/Client/Factions/FactionCreator.cs
  Source/Client/Factions/FactionSidebar.cs
  Source/Client/Factions/Page_ChooseIdeo_Multifaction.cs
  Source/Client/Factions/Page_ConfigureStartingPawns_Multifaction.cs
  Source/Client/Networking/HostUtil.cs
  Source/Client/Patches/MapSetup.cs
  Source/Client/Saving/SavingPatches.cs
  Source/Client/Syncing/Dict/SyncDictRimWorld.cs
  Source/Client/Util/MpUI.cs
Labels: 1.5, multifaction

#527 Fix #521
  Source/Client/Syncing/Game/SyncActions.cs
  Source/Client/Syncing/Handler/SyncAction.cs
Labels: fix, 1.5

#532 Integrate IsFragmented into PacketHandler
  Source/Client/Networking/State/ClientJoiningState.cs
  Source/Client/Networking/State/ClientLoadingState.cs
  Source/Client/Networking/State/ClientPlayingState.cs
  Source/Common/Networking/MpConnectionState.cs
  Source/Common/Networking/PacketHandlerAttribute.cs
  Source/Common/Networking/State/ServerPlayingState.cs
Labels: enhancement

#530 Introduce Byte{Reader,Writer}.{Read,Write}Enum
  Source/Client/Networking/JoinData.cs
  Source/Client/Networking/NetworkingLiteNet.cs
  Source/Client/Networking/NetworkingSteam.cs
  Source/Client/Networking/State/ClientJoiningState.cs
  Source/Client/Networking/State/ClientPlayingState.cs
  Source/Client/Session/MultiplayerSession.cs
  Source/Client/Session/PlayerInfo.cs
  Source/Client/Util/Extensions.cs
  Source/Common/ByteReader.cs
  Source/Common/ByteWriter.cs
  Source/Common/Networking/ConnectionBase.cs
  Source/Common/Networking/State/ServerJoiningState.cs
  Source/Common/Networking/State/ServerPlayingState.cs
  Source/Common/PlayerManager.cs
  Source/Common/ScheduledCommand.cs
  Source/Common/ServerInitData.cs
  Source/Common/ServerPlayer.cs
  Source/Common/Syncing/Logger/LoggingByteReader.cs
  Source/Common/Syncing/Logger/LoggingByteWriter.cs
  Source/Common/Util/EnumCache.cs
  Source/Common/Version.cs
Labels: enhancement

#557 Deterministic HashCombines
  Source/Client/Patches/HashCodes.cs
  Source/Client/Util/DeterministicHash.cs
Labels: enhancement, 1.6

#560 Update in-game debug layout, add transparency
  Source/Client/UI/IngameDebug.cs
Labels: enhancement, 1.6

#549 Variable Tick Rate
  Source/Client/AsyncTime/AsyncTimeComp.cs
  Source/Client/AsyncTime/AsyncWorldTimeComp.cs
  Source/Client/Patches/VTRSyncPatch.cs
  Source/Common/CommandType.cs
  Source/Common/Networking/State/ServerPlayingState.cs
  Source/Common/PlayerManager.cs
  Source/Common/ServerPlayer.cs
Labels: enhancement, 1.6

#553 Prettify debug information panel
  Source/Client/OnMainThread.cs
  Source/Client/UI/DebugPanel/DebugLine.cs
  Source/Client/UI/DebugPanel/DebugSection.cs
  Source/Client/UI/DebugPanel/PerformanceCalculator.cs
  Source/Client/UI/DebugPanel/PerformanceRecorder.cs
  Source/Client/UI/DebugPanel/StatusBadge.cs
  Source/Client/UI/DebugPanel/SyncDebugPanel.cs
  Source/Client/UI/IngameUI.cs
Labels: enhancement, waiting on merge, 1.6

#575 Fix: Starting items not marked as forbidden
  Source/Client/Factions/Forbiddables.cs
Labels: fix, 1.6

#584 Extended support for fragmented packets and handling them. Improved download dialog
  Source/Client/Networking/NetworkingSteam.cs
  Source/Client/Networking/State/ClientLoadingState.cs
  Source/Client/Windows/ConnectingWindow.cs
  Source/Common/ByteReader.cs
  Source/Common/Networking/ConnectionBase.cs
  Source/Common/Networking/FragmentedPacket.cs
  Source/Common/Networking/MpConnectionState.cs
  Source/Common/Networking/NetworkingLiteNet.cs
  Source/Common/Networking/PacketHandlerAttribute.cs
  Source/Common/Version.cs
Labels: enhancement, 1.6

#582 Performance recorder - Circular buffer, general improvements
  Source/Client/UI/DebugPanel/PerformanceRecorder.cs
  Source/Client/UI/DebugPanel/SyncDebugPanel.cs
Labels: enhancement, low priority, 1.6

#588 Fix scenario research lost on reconnect (#585)
  Source/Client/Factions/FactionCreator.cs
Labels: fix, 1.5, multifaction, 1.6

#592 Removing obsolete workaround #535 fixed by #575
  Source/Client/Factions/FactionCreator.cs
Labels: 1.5, 1.6

#593 Fix incorrect class casts
  Source/Client/AsyncTime/TimeControlUI.cs
  Source/Client/Factions/Blueprints.cs
  Source/Client/Factions/MultifactionPatches.cs
  Source/Client/Patches/AllGroupsPatch.cs
  Source/Client/Patches/Determinism.cs
  Source/Client/Patches/Patches.cs
  Source/Client/Persistent/ISwitchToMap.cs
Labels: fix, 1.5, 1.6

#595 Added fix for fish determinism
  Source/Client/Patches/Odyssey.cs
Labels: fix, desync, high priority, 1.6

#596 Clear PortraitsCache post faction creation
  Source/Client/Factions/FactionCreator.cs
Labels: fix, 1.6

#599 Update max packet size validation to use MaxFragmentPacketTotalSize
  Source/Common/Networking/ConnectionBase.cs
Labels: fix, high priority, 1.6

#602 Fixed plan implementation to work when multiple maps are loaded.
  Source/Client/AsyncTime/AsyncTimeComp.cs
  Source/Client/MultiplayerStatic.cs
  Source/Client/Patches/Designators.cs
  Source/Client/Patches/Plans.cs
  Source/Client/Syncing/Dict/SyncDictMisc.cs
Labels: fix, 1.6
