Repository rwmt/Multiplayer, pull requests merged in 2025-09, with the labels that each got.

#664 Fix syncing of CompUsable that trigger another targetter
  Source/Client/Patches/Feedback.cs
  Source/Client/Syncing/Game/SyncMethods.cs
Labels: fix, 1.6

#670 Make plans faction-based
  Source/Client/Comp/Map/FactionMapData.cs
  Source/Client/Comp/Map/MultiplayerMapComp.cs
Labels: enhancement, multifaction, 1.6

#673 Decouple LogNode from PacketLogWindow
  Source/Client/Desyncs/LogGenerator.cs
  Source/Client/Util/Extensions.cs
  Source/Client/Windows/PacketLogWindow.cs
  Source/Common/Syncing/Logger/LogNode.cs
Labels: enhancement, 1.6

#675 Extra null safety for faction data, fix errors with #670
  Source/Client/Comp/Map/FactionMapData.cs
  Source/Client/Comp/World/FactionWorldData.cs
Labels: fix, 1.6

#667 Trigger desync debug action, faster desync report generation, and separated metadata in the report
  Source/Client/Debug/DebugActions.cs
  Source/Client/Debug/DebugSync.cs
  Source/Client/Desyncs/ClientSyncOpinion.cs
  Source/Client/Desyncs/LogGenerator.cs
  Source/Client/Desyncs/MapRandomStateData.cs
  Source/Client/Desyncs/MetadataGenerator.cs
  Source/Client/Desyncs/SaveableDesyncInfo.cs
  Source/Client/Desyncs/StackTraceLogItem.cs
  Source/Client/Desyncs/SyncCoordinator.cs
  Source/Client/Multiplayer.csproj
  Source/Client/Util/CollectionExtensions.cs
  Source/Client/Util/HarmonyUtil.cs
  Source/Client/Windows/DesyncedWindow.cs
  Source/MultiplayerLoader/MultiplayerLoader.cs
Labels: enhancement, 1.6

#668 Improve handling of packets when loading
  Source/Client/Networking/State/ClientBaseState.cs
  Source/Client/Networking/State/ClientLoadingState.cs
  Source/Client/Networking/State/ClientPlayingState.cs
  Source/Client/OnMainThread.cs
  Source/Common/MultiplayerServer.cs
  Source/Common/Networking/State/ServerPlayingState.cs
Labels: enhancement, 1.6

#671 Use dedicated PacketHandlerInvoker delegate for handling packets
  Source/Common/Networking/AsyncConnectionState.cs
  Source/Common/Networking/MpConnectionState.cs
  Source/Common/Networking/PacketHandlerAttribute.cs
Labels: enhancement, 1.6

#690 Update RimWorld version
  Source/Client/Multiplayer.csproj
  Source/Common/Common.csproj
  Source/MultiplayerLoader/MultiplayerLoader.csproj
Labels: 1.6

#693 Do not abuse DefInfo for storing status data
  Source/Client/Networking/State/ClientJoiningState.cs
  Source/Common/Util/DefInfo.cs
Labels: enhancement, 1.6

#694 Add missing import to VersionChecker
  Source/Client/Util/VersionChecker.cs
Labels: fix, 1.6

#695 Expand PR workflow checks
  .github/workflows/pr-check.yml
  Source/Tests/Tests.csproj
Labels: enhancement

#701 Add installation instructions to the continuous release
  .github/workflows/alpha-notes.md
  .github/workflows/build-beta.yml
Labels: enhancement

#699 Fix the SyncDebugPanel having content cut off
  Source/Client/UI/DebugPanel/SyncDebugPanel.cs
Labels: fix, 1.6

#698 DeferredStackTracingImpl refactor
  Source/Client/Debug/DebugActions.cs
  Source/Client/Debug/DebugSync.cs
  Source/Client/Desyncs/DeferredStackTracing.cs
  Source/Client/Desyncs/StackTraceLogItem.cs
  Source/Client/UI/DebugPanel/SyncDebugPanel.cs
  Source/Client/UI/IngameDebug.cs
  Source/Common/DeferredStackTracingImpl.cs
Labels: enhancement, 1.6

#702 Fix VTRSync player count tracking
  Source/Client/Multiplayer.cs
  Source/Client/Patches/VTRSyncPatch.cs
  Source/Common/Networking/State/ServerPlayingState.cs
  Source/Common/PlayerManager.cs
  Source/Common/ServerPlayer.cs
Labels: fix, 1.6

#703 Fix feedback for drafted pawn move order
  Source/Client/Patches/Feedback.cs
  Source/Client/Syncing/Game/SyncDelegates.cs
Labels: fix, 1.6

#700 Add dependabot that updates languages submodule
  .github/dependabot.yaml
Labels: enhancement

#706 DebugModeLabel: fix cut off text when Disable tiny font is enabled
  Source/Client/UI/IngameDebug.cs
Labels: fix, 1.6

#712 VTRSync: mapIndex -> mapId
  Source/Client/Patches/VTRSyncPatch.cs
  Source/Common/Networking/State/ServerPlayingState.cs
  Source/Common/PlayerManager.cs
  Source/Common/ServerPlayer.cs
Labels: enhancement, 1.6

#713 PerformanceRecorder: fix saving exception
  Source/Client/Multiplayer.cs
  Source/Client/UI/DebugPanel/PerformanceRecorder.cs
Labels: fix, 1.6

#714 VersionChecker: ignore dirty Git hashes for continuous releases
  Source/Client/Util/VersionChecker.cs
Labels: fix, 1.6

#715 SyncDebugPanel: fix text clipping when tiny font is disabled
  Source/Client/UI/DebugPanel/SyncDebugPanel.cs
  Source/Client/Util/RectExtensions.cs
Labels: fix, 1.6

#717 Reduce MultiplayerServer.initData API surface and simplify it
  Source/Client/Networking/HostUtil.cs
  Source/Common/MultiplayerServer.cs
  Source/Common/Networking/State/ServerJoiningState.cs
  Source/Server/Server.cs
  Source/Tests/ServerTest.cs
Labels: enhancement, 1.6

#711 Add experimental debug-only file association for Multiplayer saves
  Source/Client/Settings/MpSettingsUI.cs
  Source/Client/Util/FileAssoc.cs
Labels: enhancement

#718 Update README.md
  README.md
Labels: enhancement

#720 Fix DebugTextWindow clipping
  Source/Client/Windows/DebugTextWindow.cs
Labels: fix, 1.6

#724 Fix PostLoadInit NullReferenceException
  Source/Client/Persistent/SessionManager.cs
Labels: fix, 1.6
